import type { NextPage } from "next";
import Head from "next/head";

const About: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{"About | Emin's Personal Website"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>About</p>
    </div>
  );
};

export default About;

export { getServerSideProps } from "../../components/Chakra";
