import type { NextPage } from "next";
import Head from "next/head";

const Blog: NextPage = () => {
  return (
    <div>
      <Head>
        <title>{"Blog | Emin's Personal Website"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Blog</p>
    </div>
  );
};

export default Blog;

export { getServerSideProps } from "../../components/Chakra";
